<a href="https://colab.research.google.com/github/Endistic/DW/blob/master/Hello_World.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hello PyThon
## Hello Python

In [1]:
print("Hello World")

Hello World


# Declare Variable
## How to declare variable in python

In [4]:
score = 100
name = " Big"
print(name + "_score is " + str(score))

 Big_score is 100


In [7]:
a = 2
b = 3
c = a + b
print(c)

5


# List
## How to use list

In [11]:
mylist = []
mylist.append("Big")
mylist.append(200)
mylist

['Big', 200]

In [12]:
len(mylist)


2

#If-ELse

In [13]:
if mylist[1] > 100 :
  print("Pass")

Pass


In [18]:
if mylist[1] > 100 :
 name = mylist[0]
 score = mylist[1]
 print(name+" "+str(score))


Big 200


In [19]:
score = 5
if score > 50 :
  print("A")
elif score > 20 :
  print("B")
else :
  print("C")
  if score == 0 :
    print(F)

C


# For loop 
## How to use for loop

In [30]:
summation = 0
for i in range(0,10) :
  print(str(i))
  summation = summation + 1
  print(summation)

0
1
1
2
2
3
3
4
4
5
5
6
6
7
7
8
8
9
9
10


In [42]:
summation = 5
for i in range(1,10) :
   result = summation + i
   print(result)

6
7
8
9
10
11
12
13
14


#NumPy

In [0]:
import numpy as np


In [47]:
number = [1,2,3,4,5,6]
np_array = np.array(1)
type(np_array)

numpy.ndarray

## Ex1


In [82]:
np_matrix = np.random.rand(10,5)
np_matrix[:,4] = np.random.randint(2,size = 10)
np_matrix


array([[0.09880362, 0.53451491, 0.14074475, 0.31998284, 1.        ],
       [0.57013362, 0.82695066, 0.69438228, 0.62795082, 0.        ],
       [0.2872121 , 0.05037056, 0.28937291, 0.95815543, 1.        ],
       [0.74877555, 0.37202913, 0.78302205, 0.22867201, 0.        ],
       [0.86129141, 0.74881572, 0.44007912, 0.25515416, 0.        ],
       [0.95922996, 0.75096905, 0.08811392, 0.13576788, 0.        ],
       [0.50360454, 0.02856433, 0.80801289, 0.23309366, 1.        ],
       [0.5295816 , 0.68770082, 0.27603879, 0.7125187 , 1.        ],
       [0.27742934, 0.52184944, 0.45244297, 0.87819507, 1.        ],
       [0.21655409, 0.87044852, 0.67819301, 0.69637007, 1.        ]])

In [0]:
import numpy as np

## Ex2

In [106]:
np_matrix2 = np.random.rand(10,5)
np_matrix2







array([[0.30500311, 0.7445735 , 0.50076642, 0.64481767, 0.49879072],
       [0.16256412, 0.34367951, 0.84021039, 0.16035163, 0.44918899],
       [0.8156262 , 0.28364924, 0.81787977, 0.65695796, 0.02064094],
       [0.58802242, 0.98486453, 0.81420829, 0.09192746, 0.51746639],
       [0.30975081, 0.36317574, 0.97155918, 0.18288863, 0.51421756],
       [0.87557973, 0.74464042, 0.71283599, 0.58158465, 0.51673363],
       [0.70932094, 0.66793292, 0.66190541, 0.21611782, 0.82193113],
       [0.32488615, 0.07716133, 0.57891761, 0.43555419, 0.69774219],
       [0.17703988, 0.1786644 , 0.90896041, 0.15967215, 0.80138984],
       [0.66983561, 0.84967367, 0.00157144, 0.48404572, 0.33191337]])

In [107]:
np_matrix3 = np.random.randint(3,size = 10)
np_matrix3

array([1, 1, 2, 1, 2, 1, 1, 2, 1, 2])

In [108]:
result = np.where(np_matrix3 == 2)
result

(array([2, 4, 7, 9]),)

In [109]:
np_matrix2[result,:]

array([[[0.8156262 , 0.28364924, 0.81787977, 0.65695796, 0.02064094],
        [0.30975081, 0.36317574, 0.97155918, 0.18288863, 0.51421756],
        [0.32488615, 0.07716133, 0.57891761, 0.43555419, 0.69774219],
        [0.66983561, 0.84967367, 0.00157144, 0.48404572, 0.33191337]]])